import { LegalPageLayout } from "../components/layout/LegalPageLayout";

const GITHUB_URL = "https://github.com/richet311/candor";

export function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="August 2026">
      <div>
        <h2>1. What Candor is</h2>
        <p>
          Candor is a personal software project built and maintained by an individual developer to demonstrate a
          transparent donation ledger. It is not a registered nonprofit, charity, payment processor, or money
          transmitter, and using it does not create any charitable, financial, or professional relationship between
          you and its creator.
        </p>
      </div>

      <div>
        <h2>2. Payments are in test mode</h2>
        <p>
          All checkout on Candor runs through Stripe in <strong>test mode</strong>. No real card is charged and no
          real funds move to any organization through this site. Any "raised" or "donated" figures you see are
          generated by test transactions or a background simulator used to demonstrate the ledger, not real gifts,
          unless otherwise labeled.
        </p>
      </div>

      <div>
        <h2>3. Nonprofit information shown on this site</h2>
        <p>
          Organization names, logos, and EIN/IRS registry details shown as "verified" are real and sourced from
          public records (the IRS Exempt Organizations data, via ProPublica's Nonprofit Explorer) solely to
          demonstrate an identity-verification feature. These organizations have not registered for, reviewed, or
          endorsed Candor, and do not receive any donations, real or otherwise, through this site.
        </p>
      </div>

      <div>
        <h2>4. Accounts</h2>
        <p>
          You may create an account with an email and password, or sign in with Google or GitHub. You're responsible
          for keeping your credentials secure. Don't use false information, impersonate someone else, or attempt to
          disrupt or gain unauthorized access to the service.
        </p>
      </div>

      <div>
        <h2>5. No warranty</h2>
        <p>
          Candor is provided "as is," for demonstration and educational purposes, without warranties of any kind,
          express or implied, including fitness for a particular purpose. It may change, break, or be taken down at
          any time without notice.
        </p>
      </div>

      <div>
        <h2>6. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, the creator of Candor is not liable for any damages arising from
          your use of, or inability to use, this site.
        </p>
      </div>

      <div>
        <h2>7. Changes</h2>
        <p>These terms may be updated as the project evolves. Continued use after a change means you accept it.</p>
      </div>

      <div>
        <h2>8. Contact</h2>
        <p>
          Questions about these terms can be raised via the project's{" "}
          <a href={GITHUB_URL} target="_blank" rel="noreferrer">
            GitHub repository
          </a>
          .
        </p>
      </div>
    </LegalPageLayout>
  );
}
